### ISSUE TITLE
Supervisor installation instructions throws errors

### ISSUE THREAD

**Issue by netsensei** [PACKED-vzw/resolver#24]
Clean install on a vagrant Ubuntu box. I've created a 'resolver' user and installed the resolver under /home/resolver/resolver

Following https://github.com/PACKED-vzw/resolver/blob/master/INSTALL.md with these settings:

/etc/supervisor/conf.d/resolver.conf:

```
[program:resolver]
directory = /home/resolver/resolver
command = bash supervisor/start_server.sh
user = resolver
autostart = true
autorestart = true
```

/home/resolver/resolver/supervisor/start_server.sh:

```
##
# Configuration settings (EDIT THESE)
##
RESOLVER_USER="resolver"
RESOLVER_NAME="resolver"
PROXY_NAME="127.0.0.1"
PROXY_PORT="8080"
RESOLVER_DIR="/home/resolver/resolver"
```

This is the error when I try to start supervisor:

```
resolver: ERROR (abnormal termination)
```

/var/log/supervisor/resolver-err.log contains:

```
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
Traceback (most recent call last):
  File "/usr/local/bin/gunicorn", line 11, in <module>
    sys.exit(run())
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/wsgiapp.py", line 74, in run
    WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 185, in run
    super(Application, self).run()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 71, in run
    Arbiter(self).run()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 196, in run
    self.halt(reason=inst.reason, exit_status=inst.exit_status)
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 292, in halt
    self.stop()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 343, in stop
    time.sleep(0.1)
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 209, in handle_chld
    self.reap_workers()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 459, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
```

So far, I could isolate the error to the venv environment not being booted correctly:

```
if [ ! -d "$c_dir""/""$server_name""/bin" ]; then
    virtualenv "$server_name"
    . "$server_name""/bin/activate"
else
    . "$server_name""/bin/activate"
fi
```

Not quite sure what's wrong with them. If I try to execute them directly from the shell, I get the same error.

```
su resolver
cd /home/resolver/resolver
bash supervisor/start_server.sh
```

Then again, this command doesn't give me any trouble at all (save for a little typo in that file: timout should be timeout!)

```
su resolver
cd /home/resolver/resolver
bash run_gunicorn.sh
```

**Comment by pieterdp** [comment]
I'm currently trying to reproduce it on our setup, but could it be that the virtual environment you used to install the requirements in is different from the one the server is trying to run in? Could you test that?

If so, the docs need updating.

**Comment by netsensei** [comment]
I'm using these versions:
- Python: 2.7.6
- virtualenv: 1.11.4

Since I'm a bit stuck running supervisor, I'm using the run_gunicorn.sh command from my bash prompt to fire up gunicorn.

**Comment by pieterdp** [comment]
I'm thinking the name of the virtualenv could be the issue. If you follow the documentation, it instructies you to create an virtualenv of the name "venv", but supervisor expects a virtualenv of the name "server". This is probably why it doesn't work, as "server" does not have the dependencies installed.

**Comment by netsensei** [comment]
Yep. Works now. I changed the virtualenv commands to match with the SERVER NAME in start_server.sh and that solved the issue.

I just manually installed the resolver, choosing a virtualenv name myself, but I wasn't aware that SERVER NAME also has to match that when you choose to integrate with supervisor later on.

Regarding all the installation commands: maybe we should consolidate those in an installation script and use shell variables in a separate dot configuration file (or global env variables)? Then we could make sure that SERVER NAME always stays in sync.
